# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Front Range Objectivism"
email: fro@frontrangeobjectivism.com
description: >- # this means to ignore newlines until "baseurl:"
  Dedicated to the understanding and advocacy of Ayn Rand's philosophy of Objectivism along the Front Range of the Colorado Rockies.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://objectivist-nexus.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: FRObjectivism
github_username:  Objectivist-Nexus

plugins:
  - jekyll-sitemap
  - jekyll-feed
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
  typographic_symbols: { hellip: ... , mdash: --- , ndash: -- , laquo: "<<" , raquo: ">>" , laquo_space: "<< " , raquo_space: " >>" }
  auto_id_stripping: true
include:      ['_pages']

# Build settings
theme: jekyll-theme-cayman

exclude:
  - Gemfile
  - Gemfile.lock
relative_permalinks: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "assets/images"
    values:
      image: true
      sitemap: false
  -
    scope:
      path: "_pages"
    values:
      layout: "default"
      permalink: /:basename/
  -
    scope:
      path: "_pages/study-groups"
    values:
      layout: "default"
      permalink: /study-groups/:basename/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
